version: "3"
services:

  krakend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    logging:
      driver: "none"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - krakend
