name: Run integration tests

on:
  push:

permissions:
  id-token: write
  contents: read # This is required for actions/checkout
  packages: read

jobs:
  test:
    name: Run tests
    uses: KL-Engineering/central-microgateway-configuration/.github/workflows/plugin-integration-test.yaml@main
    with:
      collection-path: krakend-wildcard-plugin.postman_collection.json
      environment-path: local-development.postman_environment.json
